package main

import (
	"testing"
)

func Test_main(t *testing.T) {
	t.Run("processTruck", func(t *testing.T) {
		t.Run("should load and unload a truck cargo", func(t *testing.T) {
			nt := &NormalTruck{id: "1", cargo: 42}
			et := &ElectricTruck{id: "2"}

			err := processTruck(nt)
			if err != nil {
				t.Fatalf("Error processing truck %s\n", err)
			}
			err = processTruck(et)
			if err != nil {
				t.Fatalf("Error processing truck %s\n", err)
			}

			// asserting
			if nt.cargo != 0 {
				t.Fatal("normal cargo should be 0")
			}
			if et.battery != -2 {
				t.Fatal("Electric truck battery should be -2")
			}

		})
	})
}

/*
// All these are autogenerated by GoLand
func TestElectricTruck_LoadCargo(t *testing.T) {
	type fields struct {
		id      string
		cargo   int
		battery float64
	}
	tests := []struct {
		name    string
		fields  fields
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			e := &ElectricTruck{
				id:      tt.fields.id,
				cargo:   tt.fields.cargo,
				battery: tt.fields.battery,
			}
			if err := e.LoadCargo(); (err != nil) != tt.wantErr {
				t.Errorf("LoadCargo() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestElectricTruck_UnloadCargo(t *testing.T) {
	type fields struct {
		id      string
		cargo   int
		battery float64
	}
	tests := []struct {
		name    string
		fields  fields
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			e := &ElectricTruck{
				id:      tt.fields.id,
				cargo:   tt.fields.cargo,
				battery: tt.fields.battery,
			}
			if err := e.UnloadCargo(); (err != nil) != tt.wantErr {
				t.Errorf("UnloadCargo() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestNormalTruck_LoadCargo(t1 *testing.T) {
	type fields struct {
		id    string
		cargo int
	}
	tests := []struct {
		name    string
		fields  fields
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t1.Run(tt.name, func(t1 *testing.T) {
			t := &NormalTruck{
				id:    tt.fields.id,
				cargo: tt.fields.cargo,
			}
			if err := t.LoadCargo(); (err != nil) != tt.wantErr {
				t1.Errorf("LoadCargo() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestNormalTruck_UnloadCargo(t1 *testing.T) {
	type fields struct {
		id    string
		cargo int
	}
	tests := []struct {
		name    string
		fields  fields
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t1.Run(tt.name, func(t1 *testing.T) {
			t := &NormalTruck{
				id:    tt.fields.id,
				cargo: tt.fields.cargo,
			}
			if err := t.UnloadCargo(); (err != nil) != tt.wantErr {
				t1.Errorf("UnloadCargo() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func Test_processTruck(t *testing.T) {
	type args struct {
		truck Truck
	}
	tests := []struct {
		name    string
		args    args
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if err := processTruck(tt.args.truck); (err != nil) != tt.wantErr {
				t.Errorf("processTruck() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}

}
*/
